name: Key Races Weekly Report

on:
  schedule:
    - cron: '0 13 * * 1'  # Mondays 13:00 UTC
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run reporter (dry run to log)
        run: |
          python -m src.key_races.main --dry-run

      - name: Build static site into docs/
        run: |
          python -m src.key_races.main --out-dir docs --write-json --no-email

      - name: Commit and push docs changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add docs
          git commit -m "chore(reports): update weekly static report" || echo "No changes to commit"
          git push
